------------------------------------------------------------------------
-- |
-- Module      :  ALife.Creatur.Wain.Iomha.Stats
-- Copyright   :  (c) Amy de Buitléir 2012-2015
-- License     :  BSD-style
-- Maintainer  :  amy@nualeargais.ie
-- Stability   :  experimental
-- Portability :  portable
--
-- Agent statistics
--
------------------------------------------------------------------------
{-# LANGUAGE TemplateHaskell #-}
module ALife.Creatur.Wain.Iomha.Stats
  (
    Stats
  ) where

import Control.Lens

data Stats = Stats
  {
    _rPopSize :: Int,
    _rDirectObjectNovelty :: Double,
    _rDirectObjectAdjustedNovelty :: Int,
    _rIndirectObjectNovelty :: Double,
    _rIndirectObjectAdjustedNovelty :: Int,
    _rOtherNovelty :: Double,
    _rOtherAdjustedNovelty :: Int,
    _rSchemaQuality :: Int,
    _rMetabolismDeltaE :: Double,
    _rChildMetabolismDeltaE :: Double,
    _rCoopDeltaE :: Double,
    _rChildCoopDeltaE :: Double,
    _rAgreementDeltaE :: Double,
    _rChildAgreementDeltaE :: Double,
    _rFlirtingDeltaE :: Double,
    _rMatingDeltaE :: Double,
    _rOtherMatingDeltaE :: Double,
    _rOtherAgreementDeltaE :: Double,
    _rOtherChildAgreementDeltaE :: Double,
    _rNetDeltaE :: Double,
    _rChildNetDeltaE :: Double,
    _rErr :: Double,
    _rBirthCount :: Int,
    _rWeanCount :: Int,
    _rCooperateCount :: Int,
    _rAgreeCount :: Int,
    _rFlirtCount :: Int,
    _rMateCount :: Int,
    _rIgnoreCount :: Int,
    _rDeathCount :: Int
  }
makeLenses ''Stats

data Summary = Summary
  {
    _rMinDirectObjectNovelty :: Double,
    _rMinDirectObjectAdjustedNovelty :: Int,
    _rMinIndirectObjectNovelty :: Double,
    _rMinIndirectObjectAdjustedNovelty :: Int,
    _rMinOtherNovelty :: Double,
    _rMinOtherAdjustedNovelty :: Int,
    _rMinSchemaQuality :: Int,
    _rMinMetabolismDeltaE :: Double,
    _rMinChildMetabolismDeltaE :: Double,
    _rMinCoopDeltaE :: Double,
    _rMinChildCoopDeltaE :: Double,
    _rMinAgreementDeltaE :: Double,
    _rMinChildAgreementDeltaE :: Double,
    _rMinFlirtingDeltaE :: Double,
    _rMinMatingDeltaE :: Double,
    _rMinOtherMatingDeltaE :: Double,
    _rMinOtherAgreementDeltaE :: Double,
    _rMinOtherChildAgreementDeltaE :: Double,
    _rMinNetDeltaE :: Double,
    _rMinChildNetDeltaE :: Double,
    _rMinErr :: Double,
    _rMinBirthCount :: Int,
    _rMinWeanCount :: Int,
    _rMinCooperateCount :: Int,
    _rMinAgreeCount :: Int,
    _rMinFlirtCount :: Int,
    _rMinMateCount :: Int,
    _rMinIgnoreCount :: Int,
    _rMinDeathCount :: Int,
    _rMaxPopSize :: Int,
    _rMaxDirectObjectNovelty :: Double,
    _rMaxDirectObjectAdjustedNovelty :: Int,
    _rMaxIndirectObjectNovelty :: Double,
    _rMaxIndirectObjectAdjustedNovelty :: Int,
    _rMaxOtherNovelty :: Double,
    _rMaxOtherAdjustedNovelty :: Int,
    _rMaxSchemaQuality :: Int,
    _rMaxMetabolismDeltaE :: Double,
    _rMaxChildMetabolismDeltaE :: Double,
    _rMaxCoopDeltaE :: Double,
    _rMaxChildCoopDeltaE :: Double,
    _rMaxAgreementDeltaE :: Double,
    _rMaxChildAgreementDeltaE :: Double,
    _rMaxFlirtingDeltaE :: Double,
    _rMaxMatingDeltaE :: Double,
    _rMaxOtherMatingDeltaE :: Double,
    _rMaxOtherAgreementDeltaE :: Double,
    _rMaxOtherChildAgreementDeltaE :: Double,
    _rMaxNetDeltaE :: Double,
    _rMaxChildNetDeltaE :: Double,
    _rMaxErr :: Double,
    _rMaxBirthCount :: Int,
    _rMaxWeanCount :: Int,
    _rMaxCooperateCount :: Int,
    _rMaxAgreeCount :: Int,
    _rMaxFlirtCount :: Int,
    _rMaxMateCount :: Int,
    _rMaxIgnoreCount :: Int,
    _rMaxDeathCount :: Int,
    _rSumPopSize :: Int,
    _rSumDirectObjectNovelty :: Double,
    _rSumDirectObjectAdjustedNovelty :: Int,
    _rSumIndirectObjectNovelty :: Double,
    _rSumIndirectObjectAdjustedNovelty :: Int,
    _rSumOtherNovelty :: Double,
    _rSumOtherAdjustedNovelty :: Int,
    _rSumSchemaQuality :: Int,
    _rSumMetabolismDeltaE :: Double,
    _rSumChildMetabolismDeltaE :: Double,
    _rSumCoopDeltaE :: Double,
    _rSumChildCoopDeltaE :: Double,
    _rSumAgreementDeltaE :: Double,
    _rSumChildAgreementDeltaE :: Double,
    _rSumFlirtingDeltaE :: Double,
    _rSumMatingDeltaE :: Double,
    _rSumOtherMatingDeltaE :: Double,
    _rSumOtherAgreementDeltaE :: Double,
    _rSumOtherChildAgreementDeltaE :: Double,
    _rSumNetDeltaE :: Double,
    _rSumChildNetDeltaE :: Double,
    _rSumErr :: Double,
    _rSumBirthCount :: Int,
    _rSumWeanCount :: Int,
    _rSumCooperateCount :: Int,
    _rSumAgreeCount :: Int,
    _rSumFlirtCount :: Int,
    _rSumMateCount :: Int,
    _rSumIgnoreCount :: Int,
    _rSumDeathCount :: Int,
    _rMeanPopSize :: Double,
    _rMeanDirectObjectNovelty :: Double,
    _rMeanDirectObjectAdjustedNovelty :: Double,
    _rMeanIndirectObjectNovelty :: Double,
    _rMeanIndirectObjectAdjustedNovelty :: Double,
    _rMeanOtherNovelty :: Double,
    _rMeanOtherAdjustedNovelty :: Double,
    _rMeanSchemaQuality :: Double,
    _rMeanMetabolismDeltaE :: Double,
    _rMeanChildMetabolismDeltaE :: Double,
    _rMeanCoopDeltaE :: Double,
    _rMeanChildCoopDeltaE :: Double,
    _rMeanAgreementDeltaE :: Double,
    _rMeanChildAgreementDeltaE :: Double,
    _rMeanFlirtingDeltaE :: Double,
    _rMeanMatingDeltaE :: Double,
    _rMeanOtherMatingDeltaE :: Double,
    _rMeanOtherAgreementDeltaE :: Double,
    _rMeanOtherChildAgreementDeltaE :: Double,
    _rMeanNetDeltaE :: Double,
    _rMeanChildNetDeltaE :: Double,
    _rMeanErr :: Double,
    _rMeanBirthCount :: Double,
    _rMeanWeanCount :: Double,
    _rMeanCooperateCount :: Double,
    _rMeanAgreeCount :: Double,
    _rMeanFlirtCount :: Double,
    _rMeanMateCount :: Double,
    _rMeanIgnoreCount :: Double,
    _rMeanDeathCount :: Double,
    _rMinPopSize :: Int,
    _rStdDevPopSize :: Double,
    _rStdDevDirectObjectNovelty :: Double,
    _rStdDevDirectObjectAdjustedNovelty :: Double,
    _rStdDevIndirectObjectNovelty :: Double,
    _rStdDevIndirectObjectAdjustedNovelty :: Double,
    _rStdDevOtherNovelty :: Double,
    _rStdDevOtherAdjustedNovelty :: Double,
    _rStdDevSchemaQuality :: Double,
    _rStdDevMetabolismDeltaE :: Double,
    _rStdDevChildMetabolismDeltaE :: Double,
    _rStdDevCoopDeltaE :: Double,
    _rStdDevChildCoopDeltaE :: Double,
    _rStdDevAgreementDeltaE :: Double,
    _rStdDevChildAgreementDeltaE :: Double,
    _rStdDevFlirtingDeltaE :: Double,
    _rStdDevMatingDeltaE :: Double,
    _rStdDevOtherMatingDeltaE :: Double,
    _rStdDevOtherAgreementDeltaE :: Double,
    _rStdDevOtherChildAgreementDeltaE :: Double,
    _rStdDevNetDeltaE :: Double,
    _rStdDevChildNetDeltaE :: Double,
    _rStdDevErr :: Double,
    _rStdDevBirthCount :: Double,
    _rStdDevWeanCount :: Double,
    _rStdDevCooperateCount :: Double,
    _rStdDevAgreeCount :: Double,
    _rStdDevFlirtCount :: Double,
    _rStdDevMateCount :: Double,
    _rStdDevIgnoreCount :: Double,
    _rStdDevDeathCount :: Double,
    _rMinPopSize :: Int
  }
makeLenses ''Summary

compile :: ([a] -> c) -> Getting a b a -> [b] -> c
compile f l = f . map (view l)

summarise :: [Stats] -> String
summarise xs =
  where compile getMean
